// Generated by CoffeeScript 1.8.0
var URL, debug, logger;

debug = require("./debug");

URL = require("url");

logger = function(settings) {
  return function(request, callback) {
    debug("Requesting " + request.method + " " + (URL.format(request.url)));
    request.on("response", function(response) {
      return debug("Received " + response.statusCode + " " + (URL.format(request.url)));
    });
    request.on("error", function(error) {
      return debug("Error " + error);
    });
    callback();
  };
};

module.exports = logger;
